import type { Pool, UserProfile } from "./types";

const DAY = 86_400_000;
const now = Date.now();

const seedUsers: Record<string, UserProfile> = {
  "7xKX...9fRd": {
    wallet: "7xKX...9fRd",
    displayName: "CryptoKing",
    xp: 12450,
    poolsCreated: ["pool-1", "pool-4"],
    poolsPledged: ["pool-2", "pool-3"],
    creaturesUnlocked: ["blobby", "sparky", "nebula", "frostbite", "voidwalker", "arcana"],
    joinedAt: now - 30 * DAY,
    referralCount: 0,
    referralXpEarned: 0,
  },
  "3mPQ...vT2e": {
    wallet: "3mPQ...vT2e",
    displayName: "NeonHunter",
    xp: 11200,
    poolsCreated: ["pool-2"],
    poolsPledged: ["pool-1", "pool-3", "pool-5"],
    creaturesUnlocked: ["blobby", "sparky", "nebula", "frostbite", "voidwalker", "arcana"],
    joinedAt: now - 25 * DAY,
    referralCount: 0,
    referralXpEarned: 0,
  },
  "9aFb...kL4w": {
    wallet: "9aFb...kL4w",
    displayName: "PoolShark",
    xp: 9800,
    poolsCreated: ["pool-3"],
    poolsPledged: ["pool-1", "pool-2"],
    creaturesUnlocked: ["blobby", "sparky", "nebula", "frostbite", "voidwalker"],
    joinedAt: now - 20 * DAY,
    referralCount: 0,
    referralXpEarned: 0,
  },
  "5dRs...mN8x": {
    wallet: "5dRs...mN8x",
    displayName: "DegenLord",
    xp: 8540,
    poolsCreated: ["pool-5"],
    poolsPledged: ["pool-1", "pool-4"],
    creaturesUnlocked: ["blobby", "sparky", "nebula", "frostbite", "voidwalker"],
    joinedAt: now - 18 * DAY,
    referralCount: 0,
    referralXpEarned: 0,
  },
  "2wEp...jH6q": {
    wallet: "2wEp...jH6q",
    displayName: "ArcadeQueen",
    xp: 7320,
    poolsCreated: [],
    poolsPledged: ["pool-1", "pool-2", "pool-3", "pool-4", "pool-5"],
    creaturesUnlocked: ["blobby", "sparky", "nebula", "frostbite", "voidwalker"],
    joinedAt: now - 15 * DAY,
    referralCount: 0,
    referralXpEarned: 0,
  },
  "8kVn...pW3y": {
    wallet: "8kVn...pW3y",
    displayName: "SolWarrior",
    xp: 5100,
    poolsCreated: ["pool-6"],
    poolsPledged: ["pool-2", "pool-5"],
    creaturesUnlocked: ["blobby", "sparky", "nebula", "frostbite", "voidwalker"],
    joinedAt: now - 12 * DAY,
    referralCount: 0,
    referralXpEarned: 0,
  },
  "4tGh...rQ9z": {
    wallet: "4tGh...rQ9z",
    displayName: "MoonRider",
    xp: 3200,
    poolsCreated: [],
    poolsPledged: ["pool-1", "pool-3"],
    creaturesUnlocked: ["blobby", "sparky", "nebula", "frostbite", "voidwalker"],
    joinedAt: now - 10 * DAY,
    referralCount: 0,
    referralXpEarned: 0,
  },
  "6yBc...sX1a": {
    wallet: "6yBc...sX1a",
    displayName: "TokenNinja",
    xp: 1800,
    poolsCreated: [],
    poolsPledged: ["pool-2", "pool-4", "pool-6"],
    creaturesUnlocked: ["blobby", "sparky", "nebula", "frostbite"],
    joinedAt: now - 7 * DAY,
    referralCount: 0,
    referralXpEarned: 0,
  },
};

const seedPools: Pool[] = [
  {
    id: "pool-1",
    name: "$DEGEN Pool",
    ticker: "DEGEN",
    description: "The original degen community pool. Ape in and earn rewards.",
    creatorWallet: "7xKX...9fRd",
    creatorName: "CryptoKing",
    targetSol: 50,
    raisedSol: 37.5,
    participants: ["3mPQ...vT2e", "9aFb...kL4w", "5dRs...mN8x", "2wEp...jH6q", "4tGh...rQ9z"],
    pledges: [
      { wallet: "3mPQ...vT2e", amount: 10, timestamp: now - 5 * DAY },
      { wallet: "9aFb...kL4w", amount: 8.5, timestamp: now - 4 * DAY },
      { wallet: "5dRs...mN8x", amount: 7, timestamp: now - 3 * DAY },
      { wallet: "2wEp...jH6q", amount: 6, timestamp: now - 2 * DAY },
      { wallet: "4tGh...rQ9z", amount: 6, timestamp: now - DAY },
    ],
    status: "active",
    createdAt: now - 10 * DAY,
    expiresAt: now + 2.6 * DAY,
  },
  {
    id: "pool-2",
    name: "$MEME Pool",
    ticker: "MEME",
    description: "The meme economy is real. Join the movement and launch $MEME.",
    creatorWallet: "3mPQ...vT2e",
    creatorName: "NeonHunter",
    targetSol: 100,
    raisedSol: 89,
    participants: ["7xKX...9fRd", "9aFb...kL4w", "2wEp...jH6q", "8kVn...pW3y", "6yBc...sX1a"],
    pledges: [
      { wallet: "9aFb...kL4w", amount: 20, timestamp: now - 6 * DAY },
      { wallet: "7xKX...9fRd", amount: 25, timestamp: now - 5 * DAY },
      { wallet: "2wEp...jH6q", amount: 15, timestamp: now - 3 * DAY },
      { wallet: "8kVn...pW3y", amount: 14, timestamp: now - 2 * DAY },
      { wallet: "6yBc...sX1a", amount: 15, timestamp: now - DAY },
    ],
    status: "active",
    createdAt: now - 12 * DAY,
    expiresAt: now + 0.77 * DAY,
  },
  {
    id: "pool-3",
    name: "$ALPHA Pool",
    ticker: "ALPHA",
    description: "Early alpha access. Get in before the crowd discovers this gem.",
    creatorWallet: "9aFb...kL4w",
    creatorName: "PoolShark",
    targetSol: 25,
    raisedSol: 8.75,
    participants: ["7xKX...9fRd", "3mPQ...vT2e", "2wEp...jH6q", "4tGh...rQ9z"],
    pledges: [
      { wallet: "3mPQ...vT2e", amount: 3, timestamp: now - 3 * DAY },
      { wallet: "2wEp...jH6q", amount: 2.5, timestamp: now - 2 * DAY },
      { wallet: "4tGh...rQ9z", amount: 3.25, timestamp: now - DAY },
    ],
    status: "active",
    createdAt: now - 5 * DAY,
    expiresAt: now + 5.1 * DAY,
  },
  {
    id: "pool-4",
    name: "$NEON Pool",
    ticker: "NEON",
    description: "Neon lights, neon gains. The cyberpunk token of the arcade.",
    creatorWallet: "7xKX...9fRd",
    creatorName: "CryptoKing",
    targetSol: 75,
    raisedSol: 75,
    participants: ["5dRs...mN8x", "2wEp...jH6q", "6yBc...sX1a"],
    pledges: [
      { wallet: "5dRs...mN8x", amount: 30, timestamp: now - 15 * DAY },
      { wallet: "2wEp...jH6q", amount: 25, timestamp: now - 14 * DAY },
      { wallet: "6yBc...sX1a", amount: 20, timestamp: now - 13 * DAY },
    ],
    status: "launched",
    createdAt: now - 20 * DAY,
    expiresAt: now - 6 * DAY,
    launchedAt: now - 12 * DAY,
  },
  {
    id: "pool-5",
    name: "$PIXEL Pool",
    ticker: "PIXEL",
    description: "Pixel-perfect gains. For the retro gaming community.",
    creatorWallet: "5dRs...mN8x",
    creatorName: "DegenLord",
    targetSol: 30,
    raisedSol: 30,
    participants: ["3mPQ...vT2e", "2wEp...jH6q", "8kVn...pW3y"],
    pledges: [
      { wallet: "3mPQ...vT2e", amount: 12, timestamp: now - 10 * DAY },
      { wallet: "2wEp...jH6q", amount: 10, timestamp: now - 9 * DAY },
      { wallet: "8kVn...pW3y", amount: 8, timestamp: now - 8 * DAY },
    ],
    status: "launched",
    createdAt: now - 14 * DAY,
    expiresAt: now - 4 * DAY,
    launchedAt: now - 7 * DAY,
  },
  {
    id: "pool-6",
    name: "$BLAZE Pool",
    ticker: "BLAZE",
    description: "Ignite the community. Blazing hot opportunities ahead.",
    creatorWallet: "8kVn...pW3y",
    creatorName: "SolWarrior",
    targetSol: 40,
    raisedSol: 12,
    participants: ["6yBc...sX1a"],
    pledges: [
      { wallet: "6yBc...sX1a", amount: 12, timestamp: now - 2 * DAY },
    ],
    status: "active",
    createdAt: now - 3 * DAY,
    expiresAt: now + 11 * DAY,
  },
];

export function generateSeedData(): { pools: Pool[]; users: Record<string, UserProfile> } {
  return { pools: seedPools, users: seedUsers };
}
